<!--
%\VignetteEngine{knitr::docco_linear}
%\VignetteIndexEntry{R Markdown with the Docco Linear Style}
-->

# The R CISM package

The R CISM package is a collaborative effort to improve the way that CISM researchers interact with data. 

## Objectives

The objectives of the R CISM package are simple:

1. Make retrieving data more simple.

2. Make data analysis more reproducible.

3. Make interaction with data more pleasurable and beautiful.

## Set up

### Installation

To use the `cism` package, you'll first need to install it. With a good internet connection, run the following from within R.

```r
if(!require(devtools)) install.packages("devtools")
install_github('joebrew/cism')
```

Once you've installed the package, you can use its functionality in any R script by simply including the following line:

```r
library(cism)
```

### Credentials

Accessing CISM databases requires permissions. All the functionality in the `cism` package can be used by calling functions with a user's credentials. However, both for the sake of ease as well as to avoid putting any confidential information into R code, it is highly recommended to create a `credentials` folder with a `credentials.yaml` file. The contents of this file should look something like this:

```
dbname: openhds
host: sap.manhica.net
port: 3306 # Use 4706 from outside of the CISM
user: your_user_name
password: your_pass_word
```

In the above, consider replacing `dbname` with the database you most often use. Replace `port` with 4706 if you work outside of the CISM. And replace the `user` and `password` fields with your name and password. If you use git, or any other form of version control, ensure that the `credentials.yaml` file is ignored by any repository viewable by others.

The `credentials/credentials.yaml` will be automatically detected by the `cism` package if in the same directory as the working directory, or if it is in a higher directory. Therefore, one should either create a `credentials/credentials.yaml` for each project, or place one `credentials/credentials.yaml` into a higher-level folder (for example "My Documents" for Windows users, or "/home/" for Linux users), under which all code resides.

## Basic use

### Retrieving data

With the `cism` package, getting data is simple. Assuming you've got a `credentials/credentials.yaml` in or above your working directory, you can simply point the `get_data` function at the database and table of your choice:

```r
residency <- get_data(tab = 'residency', dbname = 'openhds')
```

The above will return the entire "residency" table from the "openhds" database.

If you're a more advanced user and want to filter, select or join directly in SQL before collecting the results into memory, you can write directly in SQL:

```r
small_residency <- get_data(query = "SELECT uuid, startDate FROM residency limit 10", dbname = 'openhds')
```

### Visualizing data

Not finished

## Advanced use

Not finished