#' Create a connection to CISM's database
#' 
#' Use a list of options (usually created through running \code{credentials_extract}) 
#' to create a connection to a CISM database. 
#' @param options_list A list of options for connecting to a database, usually generated by calling \code{credentials_extract()}
#' @export

# This function is used in conjunction with credentials_extract() (above) 
# and fetch_db() (below)
credentials_connect <- function(options_list){

  # Attach packages  
  require(dplyr)

  # Establish connection with database
  connection_object <- do.call(src_mysql, options_list)
  
  # Return the connection object
  return(connection_object)
}
